# -*- coding: utf-8 -*-
"""WEEK 2.1 (Supervised Learning).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qLrr5t_ECxcYSFsv5gYvW3C3ztfGMf4W
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext autoreload
# %autoreload 2

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo, list_available_datasets
import pprint

"""## List Available Datasets
### **Print a list of datasets that can be imported via `fetch_ucirepo`**
"""

list_available_datasets()
list_available_datasets(filter='aim-ahead')   # only list datasets for AIM-AHEAD project
list_available_datasets(search='diabe')

"""### **Should not work for datasets that are not part of the list**"""

try:
    fetch_ucirepo(name='defungi')
    # # test invalid inputs
    # fetch_ucirepo(name='heart diseaseeeee')
    # fetch_ucirepo(id=10000)
except Exception as e:
    print(e)

"""## **Import dataset by ID**"""

sepsis = fetch_ucirepo(id=827)

"""### **Metadata**"""

pprint.pp(sepsis.metadata)

sepsis.metadata.target_col

sepsis.metadata.intro_paper.title

sepsis.metadata.additional_info.summary

"""### **Data**
**IDs, features, and targets are included as separate dataframes, along with an "original" that combines all of them.**
"""

sepsis.data.features

sepsis.data.targets

sepsis.data.ids   # this dataset no IDs

sepsis.data.original

sepsis.data.headers

"""### **Variable Info**

**Displayed in a dataframe format**
"""

sepsis.variables

"""## Import by Name"""

glioma = fetch_ucirepo(name='glioma')
glioma.data.features

from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=189)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)

X

